#!/bin/bash

case "$*" in
    "input list"*)
        shift 2
        exec ./input-list.sh "$@"
        ;;
    "input create"*)
        shift 2
        exec ./input-create.sh "$@"
        ;;
    "input delete"*)
        shift 2
        exec ./input-delete.sh "$@"
        ;;
    "output list"*)
        shift 2
        exec ./output-list.sh
        ;;
    "output create"*)
        shift 2
        exec ./output-create.sh "$@"
        ;;
    "appliance list"*)
        shift 2
        exec ./appliance-list.sh
        ;;
    "appliance delete"*)
        shift 2
        exec ./appliance-delete.sh "$@"
        ;;
    *)
        echo >&2 "Unknown subcommand: $1 $2"
        exit 1
    ;;
esac
