#!/bin/bash

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")

case "$*" in
    "input list"*)
        shift 2
        exec "$script_dir/input-list.sh" "$@"
        ;;
    "input create"*)
        shift 2
        exec "$script_dir/input-create.sh" "$@"
        ;;
    "input delete"*)
        shift 2
        exec "$script_dir/input-delete.sh" "$@"
        ;;
    "output list"*)
        shift 2
        exec "$script_dir/output-list.sh" "$@"
        ;;
    "output show"*)
        shift 2
        exec "$script_dir/output-show.sh" "$@"
        ;;
    "output create"*)
        shift 2
        exec "$script_dir/output-create.sh" "$@"
        ;;
    "output update"*)
        shift 2
        exec "$script_dir/output-update.sh" "$@"
        ;;
    "output delete"*)
        shift 2
        exec "$script_dir/output-delete.sh" "$@"
        ;;
    "appliance list"*)
        shift 2
        exec "$script_dir/appliance-list.sh"
        ;;
    "appliance delete"*)
        shift 2
        exec "$script_dir/appliance-delete.sh" "$@"
        ;;
    "group list"*)
        shift 2
        exec "$script_dir/group-list.sh" "$@"
        ;;
    *)
        echo >&2 "Unknown subcommand: $1 $2"
        exit 1
    ;;
esac
